= Gradle

* https://gradle.org[site],
https://discuss.gradle.org/c/help-discuss[forum],
https://blog.gradle.org/[blog]

* Установка

** Скачать https://gradle.org/releases[последнюю версию]

** Распаковать архив, например, в каталог C:\app

** В системную переменную PATH добавить, например, C:\app\gradle-4.3.1\bin

[TIP]
====
Необходима JDK или JRE версии 7 и выше
====

* Версия
```
gradle -v
```

* Свойства
```
gradle -q properties
```

* Задачи
```
gradle -q tasks
```

* Зависимости
```
gradlew -q dependencies
```

* Запуск задачи без выполнения
```
gradlew --dry-run :helloWorld
```

* Запуск задачи с обязательным выполнением
```
gradlew –rerun-tasks :helloWorld
```

* Запуск задачи с получением отчета профилирования
```
gradlew :helloWorld --profile
```

* Управления зависимостями и порядком выполнения задач: dependsOn, mustRunAfter, finalizedBy

[TIP]
====
* https://github.com/gradle/gradle-native[gradle-native]
====

== Отладка сборки

* Настроить
```
set GRADLE_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
```

* Запустить сборку (например, задачу hello)
```
gradle hello --no-daemon -Dorg.gradle.debug=true
```
и процесс сборки остановится с сообщением "Daemon will be stopped at the end of the build stopping after processing"

* Добавить в IDEA debug-конфигурацию по шаблону "Defaults/Remote" и с настройками по умолчанию, запустить эту конфигурацию. Процесс сборки продолжится и остановится на breakpoint-е

== Plugins

* https://github.com/Transmode/gradle-docker[se.transmode.gradle:gradle-docker]
[TIP]
====
20170129: Похоже что самый популярный
====

== Полезное

https://docs.gradle.org/current/userguide/working_with_files.html#sec:file_collections["Chapter 20. Working With Files"],
https://guides.gradle.org/using-the-worker-api/["Using the Worker API"]

* Переопределить задачу
```
task helloWorld(overwrite: true) { }
```

* Сборка без прогона тестов
```
gradle build -x test
```


* Обычная (не rich) консоль
```
gradle ... --console=plain
```

== Разработка плагинов

* https://docs.gradle.org/current/userguide/pt06.html["The Software model"]
(https://docs.gradle.org/current/userguide/software_model.html["Rule based model configuration"],
https://docs.gradle.org/current/userguide/software_model_extend.html["Extending the software model"])

[WARNING]
====
20170824 объявлено об остановке этих работ (см. https://blog.gradle.org/state-and-future-of-the-gradle-software-model["State and future of the Gradle Software Model"])
====


