= Chrome

* быстрые клавиши (Windows)

** окна/вкладки

Ctrl + N — новое окно.

Ctrl + T — новая вкладка.

Ctrl + Shift + N — новое окно в режиме инкогнито.

Ctrl + клик — открытие ссылки в новой фоновой вкладке.

Ctrl + Shift + клик — открытие ссылки в новой вкладке с переключением на неё.

Shift + клик — открытие ссылки в новом окне.

Ctrl + Shift + T — восстановление последней закрытой вкладки (до 10 вкладок).

Ctrl + W — закрытие активной вкладки или всплывающего окна.

Ctrl + Tab — переключение между вкладками.

** навигация/контент

Ctrl + S — сохранение страницы.

Ctrl + P — печать страницы.

F5 или Ctrl + R — обновление страницы.

Ctrl + F5 или Shift + F5 — принудительное обновление (без учёта кеша).

Esc — отмена загрузки страницы.

Ctrl + F — поиск.

Ctrl + U — исходный код страницы.

Ctrl + D — закладка для текущей страницы.

Ctrl + Shift + D — закладки для всех открытых страниц.

F11 — полноэкранный режим.

Ctrl + плюс и Ctrl + минус — изменение масштаба страницы.

Ctrl + 0 — стандартный масштаб страницы.

Пробел — поэкранная прокрутка страницы.

Home — переход в начало страницы.

End — переход в конец страницы.

Shift + колёсико мыши — прокрутка страницы вправо или влево.

** адресная строка

Ctrl + L — перемещение курсора в адресную строку.

Ctrl + L — выделение URL или текста в адресной строке.

Alt + Enter — открытие URL в новой вкладке.

** настройки/функции

Alt + F или F10 — настройки.

Ctrl + Shift + B — отображение и скрытие панели закладок.

Ctrl + H — история.

Ctrl + J — загрузки.

Shift + Esc — диспетчер задач.

Ctrl + Shift + J — инструменты разработчика.

Ctrl + Shift + Delete — очистка истории.

Ctrl + Shift + M — переключение между аккаунтами пользователей.
