= Angular

* Ссылки:
https://angular.io[сайт],
https://www.npmjs.com/package/@angular/cli[npm],
https://angular.io/guide/router[Routing & Navigation]

* Полезное:
https://sass-scss.ru/guide/[Основы Sass]

== Angular CLI

* Установка
```
npm install -g @angular/cli
```

* Версия
```
ng -v
```

* Создать новый проект
+
```
ng new my-app --style scss
cd my-app
```

* Сборка и запуск

** dev-версия
+
```
ng serve
```

** prod-версия
+
```
ng serve –prod
```

[TIP]
====
Вход
```
start http://localhost:4200
```
или link:localhost:4200[localhost:4200]
====

* Конфигурация Webpack

По умолчанию Angular CLI использует свою конфигурацию Webpack (находится в каталоге node_modules):
```
ng serve --> npm start
ng build --> npm run build
ng e2e   --> npm run e2
```
Собственную конфигурации Webpack для проекта можно создать:
```
ng eject
```
и тогда в корневом каталоге проекта создастся файл webpack.config.js, который далее можно будет редактировать.
Если требуется отменить проектную конфигурацию Webpack, то в файле .angular.cli.json должно быть
```
"project": {
  ...
  "ejected": false
}
```

* Создание модуля
```
ng generate module MyModuleA
```
или
```
ng g m MyModuleA
```

* Создание сервиса
```
ng generate service MyServiceA
```
или
```
ng g s MyServiceA
```
или (сервис модуля)
```
ng g s MyModuleA/MyServiceA
```

* Создание компонента
```
ng generate component MyComponentA
```
или
```
ng g c MyComponentA
```

* Создание класса
```
ng generate class MyClassA
```
или
```
ng g cl MyClassA
```

* Полезное:

https://medium.com/@tomastrajan/6-best-practices-pro-tips-for-angular-cli-better-developer-experience-7b328bc9db81[6 Best Practices & Pro Tips when using Angular CLI],
https://github.com/angular/angular-cli/wiki/stories-proxy[Proxy To Backend],
https://webpack.github.io/docs/webpack-dev-server.html#proxy[webpack-dev-server:Proxy],
https://github.com/chimurai/http-proxy-middleware#options[http-proxy-middleware:Options]

== Angular HttpClient

* Полезное:
https://habrahabr.ru/post/336280/["Основы Angular: HttpClient"],
https://medium.com/spektrakel-blog/angular-testing-snippets-httpclient-d1dc2f035eb8["Angular Testing Snippets: the new HttpClient"],
https://medium.com/codingthesmartway-com-blog/angular-4-3-httpclient-accessing-rest-web-services-with-angular-2305b8fd654b["Angular 4.3 HttpClient (Accessing REST Web Services With Angular)"],
https://blog.angularindepth.com/the-new-angular-httpclient-api-9e5c85fe3361[The new Angular HttpClient API],
https://alligator.io/angular/httpclient-intro/[Introduction to Angular's HttpClient]

== Angular Material

* Ссылки: https://github.com/angular/material2[GitHub],
https://material.angular.io/guide/getting-started[Getting started],
https://material.angular.io/components/categories[components],
https://material.io/icons/[icons],
https://material.io/guidelines/[design guide],
https://material-components-web.appspot.com/[design components]

* Установка
```
npm install --save @angular/material
npm install --save @angular/cdk
npm install --save @angular/animations
```

* Версия
```
npm view @angular/material version
```

* Полезное:

https://github.com/tomastrajan/angular-ngrx-material-starter[angular-ngrx-material-starter (git)],
https://tomastrajan.github.io/angular-ngrx-material-starter#/about[angular-ngrx-material-starter (demo)],
https://medium.com/@tomastrajan/the-complete-guide-to-angular-material-themes-4d165a9d24d1[angular-ngrx-material-starter (blog)]

https://github.com/angular/material.angular.io[material.angular.io (git)],

https://blog.thoughtram.io/angular/2017/05/23/custom-themes-with-angular-material.html[CUSTOM THEMES WITH ANGULAR MATERIAL],

https://habrahabr.ru/post/335318/[Хабр. "Angular 4 Material. Часть 1 — Создание и настройка проекта"]

== Angular Flex Layout

* Ссылки: https://github.com/angular/flex-layout[GitHub],
https://www.npmjs.com/package/@angular/flex-layout[npm],
https://tburleson-layouts-demos.firebaseapp.com/#/docs[demo],
https://github.com/angular/flex-layout/wiki/API-Documentation[API]

* Полезное:

https://alligator.io/angular/flex-layout["Flex Layout for Angular"],
https://www.diycode.cc/projects/angular/flex-layout["Flex Layout"],
http://mean-dev.info/sticky-footer-angular-2-flex-layout/["Прилипающий футер (sticky footer) на Angular 2+ и Flex-layout"],
https://embed.plnkr.co/plunk/gPY4rD["Custom breakpoints for @angular/flex-layout (Plunker)"],

https://themeforest.net/item/fury-angular-2-material-design-admin-template/19325966["Fury - Angular 5 Material Design Admin Template"],
http://fury.visurel.com/components/snack-bar[demo]

== AGM - Angular Google Maps

* Ссылки: https://github.com/SebastianM/angular-google-maps[GitHub],
https://www.npmjs.com/package/@agm/core[npm]

== ng2-google-charts

* Ссылки: https://github.com/gmazzamuto/ng2-google-charts[GitHub],
https://www.npmjs.com/package/ng2-google-charts[npm]
