= Angular

* Ссылки:
https://angular.io[сайт],
https://www.npmjs.com/package/@angular/cli[npm]

== Angular CLI

* Полезное

https://habrahabr.ru/post/335318/[Хабр. "Angular 4 Material. Часть 1 — Создание и настройка проекта"],

https://github.com/angular/material.angular.io[material.angular.io (git)]

* Установка
```
npm install -g @angular/cli
```

* Версия
```
ng -v
```

* Создать новый проект
+
```
ng new my-app --style scss
cd my-app
```

* Сборка и запуск

** dev-версия
+
```
ng serve
```

** prod-версия
+
```
ng serve –prod
```

[TIP]
====
Вход
```
start http://localhost:4200
```
или link:localhost:4200[localhost:4200]
====

* Конфигурация Webpack

По умолчанию Angular CLI использует свою конфигурацию Webpack (находится в каталоге node_modules):
```
ng serve --> npm start
ng build --> npm run build
ng e2e   --> npm run e2
```
Собственную конфигурации Webpack для проекта можно создать:
```
ng eject
```
и тогда в корневом каталоге проекта создастся файл webpack.config.js, который далее можно будет редактировать.
Если требуется отменить проектную конфигурацию Webpack, то в файле .angular.cli.json должно быть
```
"project": {
  ...
  "ejected": false
}
```

* Создание модуля
```
ng generate module MyModuleA
```
или
```
ng g m MyModuleA
```

* Создание сервиса
```
ng generate service MyServiceA
```
или
```
ng g s MyServiceA
```
или (сервис модуля)
```
ng g s MyModuleA/MyServiceA
```

* Создание компонента
```
ng generate component MyComponentA
```
или
```
ng g c MyComponentA
```

* Создание класса
```
ng generate class MyClassA
```
или
```
ng g cl MyClassA
```

== Angular Material

* Ссылки: https://github.com/angular/material2[GitHub],
https://material.angular.io/guide/getting-started[Getting started]

* Установка
```
npm install --save @angular/material
npm install --save @angular/cdk
npm install --save @angular/animations
```

* Версия
```
npm view @angular/material version
```

* Полезное:

https://github.com/tomastrajan/angular-ngrx-material-starter[angular-ngrx-material-starter (git)],
https://tomastrajan.github.io/angular-ngrx-material-starter#/about[angular-ngrx-material-starter (demo)],
https://medium.com/@tomastrajan/the-complete-guide-to-angular-material-themes-4d165a9d24d1[angular-ngrx-material-starter (blog)]

== Angular Material

* Полезное:

https://sass-scss.ru/guide/[Основы Sass]
