= ArchLinux

X-терминал
```
termite
```

== Установка

[TIP]
====
Полезное

* http://dobroserver.ru/minimalistichnoe-okruzhenie-s-arch-linux["Минималистичное окружение с Arch Linux"]
* https://wiki.archlinux.org/index.php/VirtualBox_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9)#.D0.93.D0.BE.D1.81.D1.82.D0.B5.D0.B2.D0.B0.D1.8F_.D0.9E.D0.A1_.D0.B7.D0.B0.D0.B2.D0.B8.D1.81.D0.B0.D0.B5.D1.82_.D0.BF.D0.BE.D1.81.D0.BB.D0.B5_.D0.B7.D0.B0.D0.BF.D1.83.D1.81.D0.BA.D0.B0_Xorg["VirtualBox"]
====

* подготовка для загрузки usb-носителя с ISO-образом ArchLinux

Запустить Image Writer
```
C:\app\imageWriter\1.0.0\Win32DiskImager.exe
```
заполнить поле Image File (например, "C:/vm/iso/archlinux-2018.03.01-x86_64.iso"),
поле Device (выбрать USB-носитель, например, F:),
нажать Write,
результат - носитель готов для загрузки

* загрузиться с ISO-дистрибутива (подготовку usb-носителя см. выше) и сменить пароль для root-а
```
passwd
```
(например, пароль: root)

[TIP]
====
.ssh
```
# запуск
systemctl start sshd

# соединение
ssh root@192.168.1.35

# соединение с хоста VirtualBox
boxmanage modifyvm arch --natpf1 "ssh,tcp,localhost,2222,,22"
ssh root@localhost -p 2222

# если "Host key verification failed"
ssh-keygen -R [localhost]:2222

# если "'xterm-termite': unknown terminal type"
export TERM=xterm
```
====

[NOTE]
====
.DNSSEC (20200627 Бридино)
```
# не работал ping
ping google.com
ping: google.com: Name or service not known
# и так
resolvectl query google.com
google.com: resolve call failed: DNSSEC validation failed: signature-expired
# здесь
nano /etc/systemd/resolved.conf
# указать
DNSSEC=false
# рестартовать
systemctl restart systemd-resolved
# посмотреть
resolvectl status
# дб
DNSSEC setting: no
```
====

[NOTE]
====
.BIOS (20200627 Бридино)
```
pacstrap -i /mnt grub-bios
arch-chroot /mnt mkinitcpio -p linux
```
====

[TIP]
====
.WiFi
```
# узнать имя интерфейса
ip link show
# поднять интерфейс
ip link set wlan0 up
# здесь
nano /etc/wpa_supplicant/example.conf
# дб
ctrl_interface=/run/wpa_supplicant
update_config=1
#
wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/example.conf
wpa_cli
> scan
> scan_results
> add_network
> set_network 0 ssid "gurv-router"
> set_network 0 psk "gurv-route-passphrase"
> enable_network 0
> save_config
> quit
dhcpcd wlan0
```
====

* создание (выбрать тип dos c bootable), форматирование и монтирование раздела на диске (для luna заменть sda на nvme0n1 , sda1 на nvme0n1p1 )
```
cfdisk /dev/sda
mkfs.ext4 /dev/sda1 -L "boot"
mount /dev/sda1 /mnt
```

* отредактировать список зеркал (строку с российским зеркалом, искать по Russia, перенести вверх списка)
```
nano /etc/pacman.d/mirrorlist
```

* установить базовые пакеты
```
pacstrap -i /mnt base base-devel linux linux-firmware
```

* подменить корневой каталог
```
arch-chroot /mnt
```

* нужные пакеты
```
pacman -S --noconfirm nano openssh dhcpcd
```

* выбрать язык (оставить только en_US.UTF-8 UTF-8 и ru_RU.UTF-8 UTF-8)
```
nano /etc/locale.gen
```

* генерация языков и язык по умолчанию
```
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
```

* установка часового пояса МСК
```
ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime.conf
```

* раскладка клавиатуры и шрифт в консоли
```
echo -e "KEYMAP=ru\nFONT=cyr-sun16\nFONT_MAP=" > /etc/vconsole.conf
```

* имя хоста
```
echo "luna" > /etc/hostname
```

* пользователь с правами админа
```
useradd -m gurv
passwd gurv
nano /etc/sudoers
```
(после строки: root ALL=(ALL) ALL добавить новую строку: gurv ALL=(ALL) ALL)

* загрузчик (для luna заменть sda на nvme0n1)
```
pacman -S --noconfirm grub
```
[NOTE]
====
.BIOS (20200719 Бридино)
```
pacman -S --noconfirm grub-bios
```
====
```
grub-install --target=i386-pc --force --recheck /dev/sda
exit
arch-chroot /mnt grub-mkconfig --output=/boot/grub/grub.cfg
genfstab -p /mnt > /mnt/etc/fstab
```

* отредактировать настройки сети
```
nano /mnt/etc/resolv.conf
```
(например, в случае VM-гостя, должно быть: nameserver 192.168.1.1)

* выключить
```
poweroff
```
и вынуть USB-носитель с ISO-образом (или на VM-хосте отключить загрузку с ISO-дистрибутива этого VM-guest)

Войти под пользователем gurv

* автозапуск и старт DHCP-клиента
```
sudo systemctl enable dhcpcd
sudo systemctl start dhcpcd
```

* настроить SSH
```
sudo nano /etc/ssh/sshd_config
```
дб:
```
PermitRootLogin yes
X11Forwarding yes
```

запустить SSH
```
sudo systemctl enable sshd
```

* перегрузка
```
reboot
```

* шрифты, раскладка клавиатуры
```
sudo pacman -S --noconfirm terminus-font ttf-dejavu ttf-liberation

sudo nano /etc/vconsole.conf
```
должно быть:
```
LOCALE=en_US.UTF-8
KEYMAP=ru
FONT="ter-v20n"
FONT_MAP=
USECOLOR="yes"
```

* звук

```
sudo pacman -S --noconfirm alsa-lib alsa-utils asoundconf
# установить карту по умолчанию
asoundconf list
asoundconf set-default-card PCH
# настроить
alsamixer
# проверить
speaker-test
```

"перевернутый" монитор
```
nano /etc/default/grub
```
должно быть
```
GRUB_CMDLINE_LINUX="fbcon=rotate:1"
```
и выполнить
```
grub-mkconfig --output=/boot/grub/grub.cfg
```

время в логах journal (компонент systemd)
```
timedatectl set-timezone Europe/Moscow
```
и проверить
```
timedatectl status
```

git / gradle / ...
```
sudo pacman -S --noconfirm git gradle nodejs npm
git config --global user.name gurv
git config --global user.email "vladimir.gurinovich@gmail.com"
```

== Диск

```
# список дисков и разделов
lsblk -f
# создать разделы для EFI и Arch
sudo cfdisk /dev/nvme0n1
#   1й - тип: "EFI System"; размер: 500M
#   2й - тип: "Linux filesystem"; размер: остальное
# отформатировать раздел EFI
sudo mkfs.fat -F32 /dev/nvme0n1p1 -n EFI
# установить GRUB в раздел EFI
mkdir -p /tmp/efi
sudo mount /dev/nvme0n1p1 /tmp/efi
sudo grub-install --efi-directory=/tmp/efi --boot-directory=/tmp/efi/EFI --bootloader-id=grub --target=x86_64-efi --removable  /dev/nvme0n1p1
# создать файл /tmp/efi/EFI/grub/grub.cfg
set timeout=3
menuentry "Arch Linux" {
 linux /boot/vmlinuz-linux rw root=UUID=f155a7de-d2e9-44c9-b6c0-d0aad60df772
 initrd /boot/initramfs-linux.img
}
# отформатировать раздел для Arch
sudo mkfs.ext4 /dev/nvme0n1p2 -L arch
# установить Arch
sudo mount /dev/nvme0n1p2 /mnt
pacstrap /mnt base base-devel linux linux-firmware
```

== mc

```
sudo pacman -S --noconfirm mc
```

== Skype

```
yay -S skypeforlinux-stable-bin
skypeforlinux
```

== Yay

```
cd /tmp
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
```

== Xorg

```
# установить
sudo pacman -S --noconfirm xf86-video-intel
sudo pacman -S --noconfirm xorg-server xorg-apps xorg-xinit
sudo pacman -S --noconfirm termite
yay -S google-chrome
ln -s /usr/bin/google-chrome-stable /opt/app/chrome

# переключение раскладки клавиатуры
nano ~/.xinitrc
# добавить строку
#setxkbmap -layout "us,ru" -option "grp:ctrl_shift_toggle"

# разрешить для всех пользователей
echo "allowed_users=anybody" > /etc/X11/Xwrapper.config

# настройка мониторов (для luna)
nano /etc/X11/xorg.conf.d/10-monitor.conf
# должно быть
#Section "Monitor"
#    Identifier  "DP1"
#    Option      "PreferredMode" "1920x1200"
#    Option      "Primary" "true"
#    Option      "Rotate" "right"
#EndSection
#
#Section "Monitor"
#    Identifier  "HDMI1"
#    Option      "PreferredMode" "1920x1200"
#    Option      "LeftOf" "DP1"
#EndSection
#
#Section "Device"
#    Identifier "Device0"
#    Driver "intel"
#    Option "TearFree" "true"
#    Option "Monitor-DP1" "DP1"
## not use
##    Option "Monitor-HDMI1" "HDMI1"
#EndSection
#
# мониторы
xrandr --output HDMI-1 --mode 1600x1200
xrandr --output DP-1 --mode 1600x1200
xrandr --output DP-1 --rotate right
```

== awesome

https://awesomewm.org/[site]

[TIP]
====
* Win+s - виджет подсказки активных горячих клавиш
* Win+Shift+q - выход
* Win+w - меню
* Win+r - командная строка
* Win+Shift+c - закрыть окно
* Win+F{1..5} — переключение между тегами
* Win+Shift+F{1..5} — переместить активное окно из текущего тега в выбранный тег
* Win+Ctrl+F{1..5} — отображать вместе окна из текущего тега и из выбранного тега(тегов)
* Win+Ctrl+Shift+F{1..5} — вкл/выкл отображения активного окна на указанном теге(тегах)
====

```
# установить
sudo pacman -S --noconfirm awesome
mkdir ~/.config
mkdir ~/.config/awesome
cp /etc/xdg/awesome/rc.lua ~/.config/awesome/
echo "exec awesome" > ~/.xinitrc

# настройка
nano ~/.config/awesome/rc.lua
# - использовать termite: дб terminal = "termite"
# - автозапуск приложений: см. autorunApps
# - отключить рисунок: в /usr/share/awesome/themes/default/theme.lua закомментировать theme.wallpaper
# - размер шрифта: в ~/.config/termite/config дб font = Monospace 16

# шрифт
nano ~/.Xresources
# должно быть
#Xft.dpi: 192.0
```

== java

```
# установить
sudo pacman -S --noconfirm jdk11-openjdk

# список
archlinux-java status
# изменить "по умолчанию"
sudo archlinux-java set java-11-openjdk
# посмотреть "по умолчанию"
archlinux-java get
```

== Docker

* установить
```
pacman -S --noconfirm docker
systemctl enable docker
systemctl start docker
docker info
gpasswd -a gurv docker
```

[TIP]
====
* 20180503: установился docker-1:18.04.0-1
* TODO пытался в /etc/docker/daemon.json указать
```
{
  "hosts": ["tcp://0.0.0.0:2376"]
}
```
, но стартует с ошибками

* в /usr/lib/systemd/system/docker.service должно быть
```
ExecStart=/usr/bin/dockerd -H 0.0.0.0:2375 -H fd://
```
====

== minikube

```
# docker (на хосте, необязателен)
eval $(minikube docker-env)
docker version
docker image ls
# dashboard
minikube dashboard --url
# ssh
minikube ssh
# проброс портов (пример)
#vboxmanage controlvm "minikube" natpf1 "http,tcp,,51926,,80"
#vboxmanage controlvm "minikube" natpf1 "https,tcp,,51927,,443"
```

== IDEA

```
# community-edition
# установить
pacman -S --noconfirm intellij-idea-community-edition
# указать java-environment jdk8-openjdk
# запуск
idea.sh

# ultimate
# скачать https://www.jetbrains.com/idea/download/#section=linux
# распаковать в /opt/app/
tar -xf idea-2019.2.tar.gz
# в файле /opt/app/idea-IU-192.5728.98/bin/idea.properties раскомментировать строки:
#   idea.config.path=${user.home}/.IntelliJIdea/config
#   idea.system.path=${user.home}/.IntelliJIdea/system
ln -sf /opt/app/idea-IU-192.5728.98/bin/idea.sh /opt/app/idea
# запуск
idea
```

== KVM

```
# Установить
# CPU
LC_ALL=C lscpu | grep Virtualization
# KVM modules
zgrep CONFIG_KVM /proc/config.gz
# VIRTIO modules
zgrep VIRTIO /proc/config.gz
lsmod | grep kvm
lsmod | grep virtio
# Nested virtualization
sudo modprobe -r kvm_intel
sudo modprobe kvm_intel nested=1
systool -m kvm_intel -v | grep nested
#
sudo usermod -a -G kvm,libvirt $(whoami)
# libvirtd
sudo systemctl enable libvirtd.service
sudo systemctl start libvirtd.service
# virt-manager
sudo pacman -S --noconfirm virt-manager
virt-manager
# пример запуска Arch
qemu-system-x86_64 \
  -drive diskimg.qcow2,format=qcow2 \
  -m 2048 -enable-kvm -M q35 \
  -cpu host -smp 4,sockets=1,cores=4,threads=1 \
  -bios /usr/share/qemu/bios.bin -boot menu=on \
  -cdrom archlinux-2017.01.01-dual.iso
```

== VirtualBox

```
# установить
sudo pacman -S --noconfirm virtualbox linux-headers net-tools
# добавить строку: vboxdrv
sudo nano /etc/modules-load.d/virtualbox.conf
# добавить строку: vboxnetadp vboxnetflt vboxpci
sudo nano /etc/modules-load.d/vbox-other-modules.conf
useradd -G vboxusers gurv
# 201811: при обновлении потребовалось (установилась версия glibc-2.28-5-x86_64)
#sudo pacman -Sy glibc
vboxmanage setproperty machinefolder /opt/vm
vboxmanage list systemproperties

# systemd
sudo nano /etc/systemd/system/vboxvmservice@.service
###
[Unit]
Description=VBox Virtual Machine %i Service
Requires=systemd-modules-load.service
After=systemd-modules-load.service

[Service]
User=username
Group=vboxusers
ExecStart=/usr/bin/VBoxHeadless -s %i
ExecStop=/usr/bin/VBoxManage controlvm %i savestate

[Install]
WantedBy=multi-user.target
###
#
useradd -G vboxusers gurv
sudo pacman -S --noconfirm virtualbox-guest-iso

# VM & systemd
systemctl enable vboxvmservice@win
systemctl start vboxvmservice@win
# X-запуск: virtualbox
# терминал: см. VBoxSDL или VBoxHeadless

# установить на гостевой ArchLinux
sudo pacman -S --noconfirm virtualbox-guest-modules-arch virtualbox-guest-utils

# создать файл
nano /etc/modules-load.d/virtualbox.conf
# со следующими строками:
#vboxguest
#vboxsf
#vboxvideo

# зарегистрировать сервис
systemctl enable vboxservice
nano ~/.xinitrc
# добавить строку
#/usr/bin/VBoxClient-all

# если нужно сжатие VDI-файла на Windows-host-е
pacman -S dcfldd
# это сделать на VM-guest перед сжатием
dcfldd if=/dev/zero of=/fillfile bs=4M
rm -rf /fillfile
# это сжатие на Windows-host
VBoxManage.exe modifyhd luna.vdi --compact

# списки виртуалок
vboxmanage list vms
vboxmanage list runningvms
```

== pacman

```
# Update the database
sudo pacman -Syy

# Версия установленного пакета
pacman -Q virtualbox

# Поиск пакетов в репозитории
pacman -Ss virtualbox

# Список установленных пакетов
pacman -Qi | grep Name

# Список файлов пакета
pacman -Ql virtualbox

# Список всех пакетов (без их зависимостей)
pacman -Qet

# Пакеты-сироты
pacman -Qdt

# Удалить пакет
pacman -R virtualbox
#
pacman -Rs virtualbox

# Очистка файловый кеш пакетов
pacman -Sc

# Обновить OC
pacman -Syu
#  внимание: если ошибка "error: required key missing from keyring", то
pacman -S archlinux-keyring
#  внимание: если ошибка "Invalid or Corrupted package (PGP signature)", то в файле /etc/pacman.conf указать
SigLevel = Never

# To install a local package, or from a website
sudo pacman -U /path/to/the/package
```

== SSH

* Добввить приватный ключ, например, для GitHub

```
eval $(ssh-agent)
#   добавить строку eval $(ssh-agent) в файл ~/.xinitrc
# новый ключ
ssh-keygen -t rsa -b 4096 -C "gurv@mail.ru"
#    ввести файл ключей: ~/.ssh/gurv-github_rsa
# старый ключ
chmod 400 /home/gurv/.ssh/github_rsa
#
ls /home/gurv/.ssh/ -l
#
ssh-add ~/.ssh/gurv-github_rsa
ssh-add -l
# удалить
# ssh-add -D
# ctrl-c из терминала
pacman -S xclip
xclip -sel clip < ~/.ssh/gurv-github_rsa.pub
#   можно сделать ctrl-c ключа на странице github
# проверка
ssh -T git@github.com
#   если не заработает, то смотреть: ssh -vT git@github.com
#
# замена https на ssh в git-репозитории
git remote -v
git remote set-url origin git@github.com:gurv/notebook.git
git remote -v
# проверить git push
```

== Slack

```
# установить
yay -S slack-desktop

# запуск
slack
```

== Torrent

```
# установить клиента
sudo pacman -S transmission-gtk

# запуск
transmission-gtk
```

== VLC (video player)

```
# установить
sudo pacman -S vlc

# запуск
vlc
```

== Разное

=== Добавление доверенного корневого сертификата

```
# доверенного корневого сертификата
cp CORP_ROOT_CA.crt /etc/ca-certificates/trust-source/anchors/
trust extract-compat
# персонального сертификата и личного ключа для SSL авторизации
pk12util -d sql:$HOME/.pki/nssdb -i ~/certs/16735976.p12
# в chromium (там import, затем перезапустить chromium)
chrome://settings/certificates
```

=== FAR
```
yay -S far2l-git
far2l
```

=== Telegram
```
yay -S telegram-desktop-bin
telegram-desktop
```

=== disk
```
# список дисков
sudo fdisk -l
# fdisk не создает раздел более 2ТБ, поэтому использовать parted
sudo parted /dev/sda
(parted) print
(parted) mklabel gpt
# размер можно увидеть командой print
#   Disk /dev/sda: 3001GB
(parted) mkpart primary 1 3001G
(parted) quit
sudo mkfs.ext4 /dev/sda1 -L "ext"
sudo mkdir /mnt/ext
sudo mount /dev/sda1 /mnt/ext
# найти UUID
ls -al /dev/disk/by-uuid/
# добавить строку в /etc/fstab
UUID=1d46ac90-62a0-471c-821a-c6a81b283657 /mnt/ext ext4 defaults 0 0
```
