= Semantic Web

The Semantic Web is an extension of the World Wide Web through standards set by the World Wide Web Consortium (W3C).[1] The goal of the Semantic Web is to make Internet data machine-readable.

* Основное:
https://www.w3.org/standards/semanticweb/#:~:text=The%20term%20%E2%80%9CSemantic%20Web%E2%80%9D%20refers,SPARQL%2C%20OWL%2C%20and%20SKOS[W3C],
https://en.wikipedia.org/wiki/Semantic_Web[Wiki]

* Полезное:
https://www.oracle.com/technetwork/database/options/semantic-tech/oow08-rdfs-owl-apps-131263.pdf[Oracle: Using OWL/RDFS for Building Semantic Web Applications],
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/rdfrm/rdf-suipport-for-apache-jena.html#GUID-3F437E3E-3B74-4CCF-9F16-B2B07B3899E8[Oracle: RDF Semantic Graph Support for Apache Jena],
https://events.static.linuxfound.org/sites/events/files/slides/SPARQL%20Optimisation%20101%20Tutorial.pdf[SPARQL Optimisation 101 Tutorial],
https://www.stardog.com/platform/[Stardog],
https://www.cambridgesemantics.com/why-anzo/[Anzo],
https://graphdb.ontotext.com/documentation/free/index.html[GraphDB],
https://habr.com/ru/post/451206/[habr: Что сейчас происходит с RDF-хранилищами?],
https://habr.com/ru/post/455008/[habr: Semantic Web и Linked Data. Исправления и дополнения],
https://habr.com/ru/post/576304/[habr: Как снизить зависимость кода от структуры данных?],
https://github.com/kracr/owl2bench[github: OWL2Bench]

== OWL

The Web Ontology Language (OWL) is a family of knowledge representation languages for authoring ontologies. Ontologies are a formal way to describe taxonomies and classification networks, essentially defining the structure of knowledge for various domains: the nouns representing classes of objects and the verbs representing relations between the objects

* Основное:
https://www.w3.org/OWL/[W3C],
https://www.w3.org/TR/owl-mapping-to-rdf/[W3C: Mapping to RDF Graphs],
https://www.w3.org/TR/owl2-manchester-syntax/[W3C: Manchester Syntax],
https://en.wikipedia.org/wiki/Web_Ontology_Language[Wiki]

== RDF

The Resource Description Framework (RDF) is a family of World Wide Web Consortium (W3C) specifications originally designed as a metadata data model. It has come to be used as a general method for conceptual description or modeling of information that is implemented in web resources, using a variety of syntax notations and data serialization formats. It is also used in knowledge management applications.

* Основное:
https://www.w3.org/RDF/[W3C],
https://en.wikipedia.org/wiki/Resource_Description_Framework[Wiki]

== RDFS

RDF Schema (Resource Description Framework Schema, variously abbreviated as RDFS, RDF(S), RDF-S, or RDF/S) is a set of classes with certain properties using the RDF extensible knowledge representation data model, providing basic elements for the description of ontologies. It uses various forms of RDF vocabularies, intended to structure RDF resources. RDF and RDFS can be saved in a triplestore, then one can entail some knowledge from them using a query language, like SPARQL.

* Основное:
https://www.w3.org/TR/2014/REC-rdf-schema-20140225/[W3C: RDF Schema 1.1],
https://en.wikipedia.org/wiki/RDF_Schema[Wiki]

== SHACL

Shapes Constraint Language (SHACL) is a World Wide Web Consortium (W3C) specification for validating graph-based data against a set of conditions. Among others, SHACL includes features to express conditions that constrain the number of values that a property may have, the type of such values, numeric ranges, string matching patterns, and logical combinations of such constraints. SHACL also includes an extension mechanism to express more complex conditions in languages such as SPARQL.

* Основное:
https://www.w3.org/TR/shacl/[W3C],
https://en.wikipedia.org/wiki/SHACL[Wiki]

== SPARQL

SPARQL (pronounced "sparkle" /ˈspɑːkəl/, a recursive acronym for SPARQL Protocol and RDF Query Language) is an RDF query language—that is, a semantic query language for databases—able to retrieve and manipulate data stored in Resource Description Framework (RDF) format.

* Основное:
https://www.w3.org/TR/rdf-sparql-query/[W3C],
https://en.wikipedia.org/wiki/SPARQL[Wiki]

=== Turtle

Terse RDF Triple Language (Turtle) is a syntax and file format for expressing data in the Resource Description Framework (RDF) data model. Turtle syntax is similar to that of SPARQL, an RDF query language. It is a common data format for storing RDF data, along with N-Triples, JSON-LD and RDF/XML.

* Основное:
https://www.w3.org/TR/turtle/[W3C],
https://en.wikipedia.org/wiki/Turtle_(syntax)[Wiki]

== Apache Jena

A free and open source Java framework for building Semantic Web and Linked Data applications.

* Основное:
https://jena.apache.org/index.html[site],
https://jena.apache.org/documentation/[docs],
https://jena.apache.org/about_jena/architecture.html[architecture],
https://github.com/apache/jena[github]

== BFO

The Basic Formal Ontology (BFO) is a small, upper level ontology that is designed for use in supporting information retrieval, analysis and integration in scientific and other domains. BFO is a genuine upper ontology. Thus it does not contain physical, chemical, biological or other terms which would properly fall within the coverage domains of the special sciences. BFO is used by more than 250 ontology-driven endeavors throughout the world.

* Основное:
https://basic-formal-ontology.org/[site],
file:///C:/Users/GurV/Downloads/BFO2-Reference.pdf[reference],
https://github.com/BFO-ontology/BFO[github]

== QUDT

QUDT presents a unified architecture for the conceptual representation of quantities, quantity kinds, units, dimensions, and data types, which lie at the core of all scientific and engineering inquiry.

* Основное:
http://www.qudt.org/pages/HomePage.html[site]

== SKOS
The Simple Knowledge Organization System (SKOS) is a common data model for sharing and linking knowledge organization systems via the Semantic Web.

* Основное:
https://www.w3.org/TR/skos-reference/[reference]

== NIF

The NLP Interchange Format (NIF) is an RDF/OWL-based format that aims to achieve interoperability between Natural Language Processing (NLP) tools, language resources and annotations.

* Основное:
https://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core/nif-core.html

== ТриниДата

* Основное:
https://trinidata.ru/[site]

* Полезное:
https://trinidata.ru/files/CookBook.pdf[Корпоративные автоматизированные системы на основе онтологических моделей: книга рецептов]
https://trinidata.ru/files/EnterpriseModeling.pdf[ОНТОЛОГИЧЕСКОЕ МОДЕЛИРОВАНИЕ ПРЕДПРИЯТИЙ. МЕТОДЫ И ТЕХНОЛОГИИ],
https://trinidata.ru/files/ArchiGraphMIRUserGuide.pdf[РУКОВОДСТВО ПОЛЬЗОВАТЕЛЯ редактора онтологий АрхиГраф.Мир],
https://trinidata.ru/files/OntoAdminGuide.pdf[РУКОВОДСТВО АДМИНИСТРАТОРА редактора онтологий Onto.pro],
https://trinidata.ru/mdm_benchmark.htm[АрхиГраф.MDM. Результаты теста быстродействия],
https://trinidata.ru/tech_tech.htm[Технологии онтологического моделирования. RDF и OWL]
