= Spring

* Ссылки:
https://spring.io/[site],
https://docs.spring.io/spring/docs/current/spring-framework-reference/[documentation],
https://github.com/spring-projects/spring-framework[GitHub],
https://repo.spring.io/webapp/#/home[repo]

== Spring Boot

* Ссылки:
https://projects.spring.io/spring-boot/[site],
https://github.com/spring-projects/spring-boot[GitHub],
https://start.spring.io/[Spring Initializr]

== Spring Security

* Полезное:
https://developer.okta.com/blog/2017/12/18/spring-security-5-oidc["Get Started with Spring Security 5.0 and OIDC"],
http://www.baeldung.com/spring-security-openid-connect["Spring Security and OpenID Connect"]
https://github.com/spring-projects/spring-security/tree/5.0.0.RELEASE/samples/boot/oauth2login["OAuth 2.0 Login Sample"],
https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/reference/htmlsingle/#jc-oauth2login["OAuth 2.0 Login Sample Documentation (есть информация о регистрации приложений на GitHub, Google, Facebook, Okta"],
https://habrahabr.ru/post/346628/["201801 Хабр: Путь запроса по внутренностям Spring Security"]

== Spring Batch

A lightweight, comprehensive batch framework designed to enable the development of robust batch applications vital for the daily operations of enterprise systems.

* Ссылки:
http://projects.spring.io/spring-batch/[site],
https://github.com/spring-projects/spring-batch[GitHub],
https://docs.spring.io/spring-batch/4.0.x/reference/html/index.html[reference],
http://download.oracle.com/otndocs/jcp/batch-1_0_revA-mrel-eval-spec/index.html[JSR-352]

* Полезное:
http://spring-projects.ru/guides/batch-processing/["Создание Batch-сервиса"],
http://javainside.ru/primer-ispolzovaniya-spring-batch-3-0-chast-1/["Spring Batch 3.0 – Часть 1: Пример использования"],
http://sboychenko.ru/spring-batch-jmstemplate/["Spring Batch + JmsTemplate"]

== Spring Kafka

The Spring for Apache Kafka (spring-kafka) project applies core Spring concepts to the development of Kafka-based messaging solutions.

* Ссылки:
http://projects.spring.io/spring-kafka/[site],
https://github.com/spring-projects/spring-kafka[GitHub],
https://docs.spring.io/spring-kafka/docs/2.1.1.BUILD-SNAPSHOT/reference/html/[reference]

* Полезное:
http://www.baeldung.com/spring-kafka["Intro to Apache Kafka with Spring"]

== Spring Data

* Включение логирования для Hibernate (файл application.yml)
```
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
```

=== Spring Data REST

* Ссылки:
https://projects.spring.io/spring-data-rest/[site],
https://docs.spring.io/spring-data/rest/docs/3.0.2.RELEASE/reference/html/[reference]

== Spring Hateoas

* Ссылки:
https://projects.spring.io/spring-hateoas/[site],
https://github.com/spring-projects/spring-hateoas[GitHub],
https://docs.spring.io/spring-hateoas/docs/0.23.0.RELEASE/reference/html/[reference]

== Spring Cloud

* Ссылки:
http://projects.spring.io/spring-cloud/[site],
https://github.com/spring-cloud[GitHub],
https://cloud.spring.io/spring-cloud-netflix/[Netflix]

* Полезное:
https://habrahabr.ru/company/jugru/blog/341026/["Хабр. Что такое Spring Cloud и как его готовить"]

=== Spring Cloud Config

Centralized external configuration management backed by a git repository. The configuration resources map directly to Spring `Environment` but could be used by non-Spring applications if desired.

* Ссылки:
https://cloud.spring.io/spring-cloud-config/[site],
https://github.com/spring-cloud/spring-cloud-config[GitHib]

=== Spring Cloud Netflix

Integration with various Netflix OSS components (Eureka, Hystrix, Zuul, Archaius, etc.). 

* Ссылки:
https://cloud.spring.io/spring-cloud-netflix/[site]

=== Spring Cloud Stream

A lightweight event-driven microservices framework to quickly build applications that can connect to external systems. Simple declarative model to send and receive messages using Apache Kafka or RabbitMQ between Spring Boot apps.

* Ссылки:
https://cloud.spring.io/spring-cloud-stream/[site],
https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/[reference],
https://github.com/spring-cloud/spring-cloud-stream[GitHub],
https://github.com/spring-cloud/spring-cloud-stream-samples[samples]

* Полезное:
http://www.baeldung.com/spring-cloud-stream["Introduction to Spring Cloud Stream"]

=== Spring Cloud Data Flow

Spring Cloud Data Flow is a toolkit for building data integration and real-time data processing pipelines.

* Ссылки:
https://cloud.spring.io/spring-cloud-dataflow/[site],
https://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.M3/reference/htmlsingle/#getting-started[reference],
https://github.com/spring-cloud/spring-cloud-dataflow[GitHub]

=== Spring Cloud Security

Provides support for load-balanced OAuth2 rest client and authentication header relays in a Zuul proxy.

=== Spring Cloud Sleuth

Distributed tracing for Spring Cloud applications, compatible with Zipkin, HTrace and log-based (e.g. ELK) tracing. 

* Ссылки:
https://cloud.spring.io/spring-cloud-sleuth/[site]

* Полезное:
https://habrahabr.ru/company/jugru/blog/341026/["Хабр. Что такое Spring Cloud и как его готовить"]

=== Spring Cloud Config

Centralized external configuration management backed by a git repository. The configuration resources map directly to Spring `Environment` but could be used by non-Spring applications if desired.

* Ссылки:
https://cloud.spring.io/spring-cloud-config/[site],
https://github.com/spring-cloud/spring-cloud-config[GitHib]

=== Spring Cloud Netflix

Integration with various Netflix OSS components (Eureka, Hystrix, Zuul, Archaius, etc.). 

* Ссылки:
https://cloud.spring.io/spring-cloud-netflix/[site]

=== Spring Cloud Stream

A lightweight event-driven microservices framework to quickly build applications that can connect to external systems. Simple declarative model to send and receive messages using Apache Kafka or RabbitMQ between Spring Boot apps.

* Ссылки:
https://cloud.spring.io/spring-cloud-stream/[site],
https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/[documentation],
https://github.com/spring-cloud/spring-cloud-stream[GitHub]

* Полезное:
http://www.baeldung.com/spring-cloud-stream["Introduction to Spring Cloud Stream"]

=== Spring Cloud Security

Provides support for load-balanced OAuth2 rest client and authentication header relays in a Zuul proxy.

=== Spring Cloud Sleuth

Distributed tracing for Spring Cloud applications, compatible with Zipkin, HTrace and log-based (e.g. ELK) tracing. 

* Ссылки:
https://cloud.spring.io/spring-cloud-sleuth/[site]

== Spring WebFlux

* Ссылки:
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html[docs],
https://github.com/spring-projects/spring-framework/tree/master/spring-webflux[git]
