= Spring

* https://spring.io/[site],
https://docs.spring.io/spring/docs/current/spring-framework-reference/[doc],
https://github.com/spring-projects/spring-framework[git],
https://repo.spring.io/webapp/#/home[repo]

== Spring Boot

* https://projects.spring.io/spring-boot/[site],
https://github.com/spring-projects/spring-boot[git],
https://start.spring.io/[Spring Initializr]

== Spring Security

* Полезное:
https://developer.okta.com/blog/2017/12/18/spring-security-5-oidc["Get Started with Spring Security 5.0 and OIDC"],
http://www.baeldung.com/spring-security-openid-connect["Spring Security and OpenID Connect"]
https://github.com/spring-projects/spring-security/tree/5.0.0.RELEASE/samples/boot/oauth2login["OAuth 2.0 Login Sample"],
https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/reference/htmlsingle/#jc-oauth2login["OAuth 2.0 Login Sample Documentation (есть информация о регистрации приложений на GitHub, Google, Facebook, Okta"],
https://habrahabr.ru/post/346628/["201801 Хабр: Путь запроса по внутренностям Spring Security"]

== Spring Batch

A lightweight, comprehensive batch framework designed to enable the development of robust batch applications vital for the daily operations of enterprise systems.

* http://projects.spring.io/spring-batch/[site],
https://github.com/spring-projects/spring-batch[git],
https://docs.spring.io/spring-batch/4.0.x/reference/html/index.html[doc],
http://download.oracle.com/otndocs/jcp/batch-1_0_revA-mrel-eval-spec/index.html[JSR-352]

* Полезное:
http://spring-projects.ru/guides/batch-processing/["Создание Batch-сервиса"],
http://javainside.ru/primer-ispolzovaniya-spring-batch-3-0-chast-1/["Spring Batch 3.0 – Часть 1: Пример использования"],
http://sboychenko.ru/spring-batch-jmstemplate/["Spring Batch + JmsTemplate"]

== Spring Kafka

The Spring for Apache Kafka (spring-kafka) project applies core Spring concepts to the development of Kafka-based messaging solutions.

* http://projects.spring.io/spring-kafka/[site],
https://github.com/spring-projects/spring-kafka[git],
https://docs.spring.io/spring-kafka/docs/2.1.1.BUILD-SNAPSHOT/reference/html/[doc]

* Полезное:
http://www.baeldung.com/spring-kafka["Intro to Apache Kafka with Spring"]

== Spring Data

* Включение логирования для Hibernate (файл application.yml)
```
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
```

=== Spring Data REST

* https://projects.spring.io/spring-data-rest/[site],
https://docs.spring.io/spring-data/rest/docs/3.0.2.RELEASE/reference/html/[doc]

== Spring Hateoas

* https://projects.spring.io/spring-hateoas/[site],
https://github.com/spring-projects/spring-hateoas[git],
https://docs.spring.io/spring-hateoas/docs/0.23.0.RELEASE/reference/html/[doc]

== Spring Cloud

* http://projects.spring.io/spring-cloud/[site],
https://github.com/spring-cloud[git],
https://cloud.spring.io/spring-cloud-netflix/[Netflix]

* Полезное:
https://habrahabr.ru/company/jugru/blog/341026/["Хабр. Что такое Spring Cloud и как его готовить"]

=== Spring Cloud Config

Centralized external configuration management backed by a git repository. The configuration resources map directly to Spring `Environment` but could be used by non-Spring applications if desired.

* https://cloud.spring.io/spring-cloud-config/[site],
https://github.com/spring-cloud/spring-cloud-config[git]

=== Spring Cloud Netflix

Integration with various Netflix OSS components (Eureka, Hystrix, Zuul, Archaius, etc.). 

* https://cloud.spring.io/spring-cloud-netflix/[site]

=== Spring Cloud Stream

A lightweight event-driven microservices framework to quickly build applications that can connect to external systems. Simple declarative model to send and receive messages using Apache Kafka or RabbitMQ between Spring Boot apps.

* https://cloud.spring.io/spring-cloud-stream/[site],
https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/[doc],
https://github.com/spring-cloud/spring-cloud-stream[git],
https://github.com/spring-cloud/spring-cloud-stream-samples[samples]

* Полезное:
http://www.baeldung.com/spring-cloud-stream["Introduction to Spring Cloud Stream"]

=== Spring Cloud Task

Spring Cloud Task allows a user to develop and run short lived microservices using Spring Cloud and run them locally, in the cloud, even on Spring Cloud Data Flow. Just add @EnableTask and run your app as a Spring Boot app (single application context).

* http://cloud.spring.io/spring-cloud-task/[site],
https://docs.spring.io/spring-cloud-task/docs/2.0.0.M3/reference/htmlsingle/[doc],
https://github.com/spring-cloud/spring-cloud-task[git].
https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-samples[samples]

=== Spring Cloud Data Flow

Spring Cloud Data Flow is a toolkit for building data integration and real-time data processing pipelines.

* https://cloud.spring.io/spring-cloud-dataflow/[site],
https://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.M3/reference/htmlsingle/#getting-started[doc],
https://github.com/spring-cloud/spring-cloud-dataflow[git]

=== Spring Cloud Data Flow Dashboard

* http://cloud.spring.io/spring-cloud-dataflow-ui/[doc],
https://github.com/spring-cloud/spring-cloud-dataflow-ui[git]

=== Spring Cloud Skipper

Skipper is a tool that allows you to discover applications and manage their lifecycle on multiple Cloud Platforms.

* https://cloud.spring.io/spring-cloud-skipper/[site],
http://docs.spring.io/spring-cloud-skipper/docs/1.0.1.RELEASE/reference/htmlsingle/#getting-started[doc],
https://github.com/spring-cloud/spring-cloud-skipper[git]

=== Spring Cloud Security

Provides support for load-balanced OAuth2 rest client and authentication header relays in a Zuul proxy.

=== Spring Cloud Sleuth

Distributed tracing for Spring Cloud applications, compatible with Zipkin, HTrace and log-based (e.g. ELK) tracing. 

* https://cloud.spring.io/spring-cloud-sleuth/[site]

* Полезное:
https://habrahabr.ru/company/jugru/blog/341026/["Хабр. Что такое Spring Cloud и как его готовить"]

=== Spring Cloud Security

Provides support for load-balanced OAuth2 rest client and authentication header relays in a Zuul proxy.

=== Spring Cloud Sleuth

Distributed tracing for Spring Cloud applications, compatible with Zipkin, HTrace and log-based (e.g. ELK) tracing. 

* https://cloud.spring.io/spring-cloud-sleuth/[site]

== Spring WebFlux

* https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html[docs],
https://github.com/spring-projects/spring-framework/tree/master/spring-webflux[git]

== Spring Flo

Spring Flo is a JavaScript library that offers a basic embeddable HTML5 visual builder for pipelines and simple graphs. This library is used as the basis of the stream builder in Spring Cloud Data Flow.

* https://github.com/spring-projects/spring-flo[git],
https://github.com/spring-projects/spring-flo#samples[samples]

== Spring Statemachine

Spring Statemachine is a framework for application developers to use state machine concepts with Spring applications.

* https://projects.spring.io/spring-statemachine/[site],
https://docs.spring.io/spring-statemachine/docs/2.0.0.RC1/reference/htmlsingle/[doc],
https://github.com/spring-projects/spring-statemachine[git],
https://github.com/spring-projects/spring-statemachine/tree/master/spring-statemachine-samples[samples]

* Полезное:
http://www.baeldung.com/spring-state-machine["A Guide to the Spring State Machine Project"]

== Spring Boot Actuator

Spring Boot Actuator includes a number of additional features to help you monitor and manage your application when it’s pushed to production. You can choose to manage and monitor your application using HTTP or JMX endpoints. Auditing, health and metrics gathering can be automatically applied to your application.

* https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready[doc],
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-actuator[git]

== SpringFox

The Springfox suite of java libraries are all about automating the generation of machine and human readable specifications for JSON APIs written using the spring family of projects. Springfox works by examining an application, once, at runtime to infer API semantics based on spring configurations, class structure and various compile time java Annotations.

* https://springfox.github.io/springfox/docs/current/[doc],
https://github.com/springfox/springfox[git]

== JavaMelody

The goal of JavaMelody is to monitor Java or Java EE applications in QA and production environments. It is not a tool to simulate requests from users, it is a tool to measure and calculate statistics on real operation of an application depending on the usage of the application by users.

"Очень удобная штука, которая встраивается в виде веб-фильтра во все запросы, да и не только в запросы, собирает кучу полезных данных и очень компактно выставляет их в виде красивой странички прямо на борту микросевиса" (ЦФТ 2018)

* https://github.com/javamelody/javamelody/wiki[git]
